### ISSUE TITLE
Move utils into utils directory

### ISSUE THREAD

**Issue by bdejong** [bdejong/smartelectronix#20]
build.ps1 and get_steinberg_sdk.py should probably be inside a utils directory...

**Comment by bdejong** [comment]
@dozius FYI, would clean up the root a bit...

**Comment by dozius** [comment]
Probably a good idea for the CI related stuff, since it servers no purpose locally. Do the yml files need to stay in the root?

build.ps1 was made with the intent to remove some tedious typing in the shell. It just happened to also be more convenient to use in the appveyor config. I'd prefer to keep in the root, but not a big deal to move it. Really just .\build versus .\utils\build

**Comment by bdejong** [comment]
> Do the yml files need to stay in the root?

Yeah...

> I'd prefer to keep in the root, but not a big deal to move it.

Let me think about it :-)

**Comment by bdejong** [comment]
WONTFIX
