### ISSUE TITLE
Alternate display options for s(M)exoscope

### ISSUE THREAD

**Issue by CraigG58** [bdejong/smartelectronix#37]
Great job, wonderful plugin... I've wanted to run this for the longest time, and could not because of the original being 32-bit. Major kudos to this developer, since now I can!

Not sure if s(M)exoscope is still being monitored on GitHub, but I wanted to submit a feature request, if that sort of thing is still being considered.

I'm currently migrating from Cakewalk to Mixbus. One of the glaring omissions I've noticed in Mixbus is the ability to monitor bus/master waveforms in real-time. I've included screen captures of this in both Cakewalk and Mixbus, for the sake of clarity. In the Cakewalk capture, the waveforms are being displayed in the editor bus/master lanes under the play head (at bottom of capture, in orange). In the Mixbus capture, the editor bus/master lanes are in red, just sitting there blank, doing absolutely nothing. Seems useless to me, and I can't imagine why Harrison does not display any useful information there.

The ability to monitor bus/master waveforms as the play head travels down those bus strip lanes is important, for a number of reasons:
- To display clipping (I can't always mix in floating point, for various reasons).
- The effect of any mixer adjustments be seen in the waveforms, instantly.
- Most importantly, a method to observe them as they relate to each other is a must-have.

Please forgive my lack on knowledge on this subject, as I'm not very familiar with C/C++, nor do I know much about its capabilities when it comes to DAW plugins.

Would one either of these things be possible?

- Add a feature which would allow s(M)exoscope output to display in-line in the plugin area of the DAW mixer strip, with adjustable height and length of sample. This would allow the monitoring of bus/master waveforms in the mixer, right next to each other. Currently, popping open multiple s(M)exoscope windows takes up a lot of display real estate, and this would totally solve that problem. 

If all of the s(M)exoscope controls could be enabled in mixer automation, that would be a great thing too.

-or-

- Display bus waveforms in the editor, as is the case with Cakewalk. I doubt this is possible, but that would be ideal, so I just have to ask.

If the s(M)exoscope developer is still monitoring GitHub, thanks much in advance for your consideration, I appreciate it!
![cakewalk editor bus-master waveform display](https://user-images.githubusercontent.com/35228033/34678634-b854b724-f461-11e7-9f7e-913b547ff0a0.png)
![mixbus editor bus-master lane display](https://user-images.githubusercontent.com/35228033/34678635-b862e22c-f461-11e7-9dd4-8242ba300c1a.png)

**Comment by bdejong** [comment]
Hi Craig. Can't you insert smexoscope as a send bus plug-in or master
plug-in? I'm unsure what exactly you mean...

On Jan 8, 2018 16:54, "CraigG58" <notifications@github.com> wrote:

Great job, wonderful plugin... I've wanted to run this for the longest
time, and could not because of the original being 32-bit. Major kudos to
this developer, since now I can!

Not sure if s(M)exoscope is still being monitored on GitHub, but I wanted
to submit a feature request, if that sort of thing is still being
considered.

I'm currently migrating from Cakewalk to Mixbus. One of the glaring
omissions I've noticed in Mixbus is the ability to monitor bus/master
waveforms in real-time. I've included screen captures of this in both
Cakewalk and Mixbus, for the sake of clarity. In the Cakewalk capture, the
waveforms are being displayed in the editor bus/master lanes under the play
head (at bottom of capture, in orange). In the Mixbus capture, the editor
bus/master lanes are in red, just sitting there blank, doing absolutely
nothing. Seems useless to me, and I can't imagine why Harrison does not
display any useful information there.

The ability to monitor bus/master waveforms as the play head travels down
those bus strip lanes is important, for a number of reasons:

   - To display clipping (I can't always mix in floating point, for various
   reasons).
   - The effect of any mixer adjustments be seen in the waveforms,
   instantly.
   - Most importantly, a method to observe them as they relate to each
   other is a must-have.

Please forgive my lack on knowledge on this subject, as I'm not very
familiar with C/C++, nor do I know much about its capabilities when it
comes to DAW plugins.

Would one either of these things be possible?

   - Add a feature which would allow s(M)exoscope output to display in-line
   in the plugin area of the DAW mixer strip, with adjustable height and
   length of sample. This would allow the monitoring of bus/master waveforms
   in the mixer, right next to each other. Currently, popping open multiple
   s(M)exoscope windows takes up a lot of display real estate, and this would
   totally solve that problem.

If all of the s(M)exoscope controls could be enabled in mixer automation,
that would be a great thing too.

-or-

   - Display bus waveforms in the editor, as is the case with Cakewalk. I
   doubt this is possible, but that would be ideal, so I just have to ask.

If the s(M)exoscope developer is still monitoring GitHub, thanks much in
advance for your consideration, I appreciate it!
[image: cakewalk editor bus-master waveform display]
<https://user-images.githubusercontent.com/35228033/34678634-b854b724-f461-11e7-9f7e-913b547ff0a0.png>
[image: mixbus editor bus-master lane display]
<https://user-images.githubusercontent.com/35228033/34678635-b862e22c-f461-11e7-9dd4-8242ba300c1a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bdejong/smartelectronix/issues/37>, or mute the thread

**Comment by CraigG58** [comment]
Hi backatcha, and thanks so much for taking the time to reply!

I probably didn't explain clearly enough, so I've attached another screen capture, this time from the Mixbus mixer.

- On the "Drums" bus, there's a plugin that comes with Mixbus called "a-Inline Scope". You can see what I mean by "inline", it displays the waveform vertically right in the plugin area when minimized. Unfortunately, the height is very small, and only the last 5 seconds of the waveform is displayed. Other than that maximum time, there's really no other useful adjustments in it. All of this makes it pretty useless, although it's sort of close to what I'm after.

- On the "Vocals" bus is s(M)exoscope. When it's minimized, all you see in the plugins area is the icon for it... You must maximize it to view the waveform. If it behaved like "a-Inline Scope" when minimized, I'd be able to see the waveforms for all those busses at the same time, without having to maximize it. Plus, the time, amp, etc. controls of s(M)exoscope are obviously so much better, and being able to adjust all of that to also affect the minimized display view would be awesome.

Hopefully that clears things up, any other questions, just let me know!
![s m exoscope operating in mixbus](https://user-images.githubusercontent.com/35228033/34686174-c8d654c4-f478-11e7-8bdb-7419913e1d66.png)

**Comment by bdejong** [comment]
Hi @CraigG58 ,

So if I understand you correctly you'd like to have a "slim"/"flat" version of Smexoscope. That could be done, but you'd have to lose most of the controls + it would be additional development...

We could talk about making something like this, but we'll have to talk about it in detail. I.e which controls you want to keep and which controls you want to drop. And... we'll need to talk about what it's worth to you... In general the plugin will stay inside a window, there is nothing I can do about that that. I.e. there will still need to be a secondary window opened, there's no way for me to embed this view inside the application. So, imagine that last screenshot but with Smexoscope being maybe 1/5th as high as what you go there...

Please contact me at bram.dejong at gmail.com. I'll close this issue...

Bram

**Comment by CraigG58** [comment]
Hi Bram!

That's fine, I just wanted to ask if something like that would be possible. I haven't seen anything like what I'm looking for in a plugin, except for the Mixbus "a-Inline Scope" I mentioned, which I just discovered is actually an LUA script.

IMHO, where these waveform monitors really belong have nothing to do with plugins anyway, that should be a function of the DAW placing them in the bus/master lanes of the editor, as Cakewalk does. Obviously, Mixbus falls short in that area... I've submitted a feature request with them as well about it, so hopefully it's implemented someday. What purpose bus and master lanes serve in a DAW editor with absolutely nothing in them, I've no idea.

Sure, go ahead and close this out. It was just a thought, but sounds like a difficult one to implement, if not impossible. It's still a wonderful plugin, and I appreciate your work and feedback to me about it very much.

- Craig
