### ISSUE TITLE
Questions regarding CLA

### ISSUE THREAD

**Issue by falkTX** [bdejong/smartelectronix#44]
Hello there.
I have interest in these plugins (specially making them work on Linux) so I have a few questions...
Do you request a CLA for every single change? I see this PR https://github.com/bdejong/smartelectronix/pull/40 was just about a README, but you still mentioned it.
(tbh I think you are just pushing developers away asking for this)

I *do not* want to sign a CLA, but want to make use of these plugins.
Any chance at all you will import changes / fixes, or do I have to maintain a fork?

**Comment by bdejong** [comment]
I require a CLA is because like that I retain the right to license the plugins as dual licensing under a commercial license. This shouldn't stop you from porting not should it stop you from forking!

If you sign the CLA I will very gladly merge any additions you come up with that makes sense! As a port doesn't really add any features I believe wanting to retain the right to license things out makes complete sense, especially considering almost all of here were licensed out commercially at some point.

Bram
